module Scenes.Main.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import Scenes.Main.GameLayer.Export as GameLayer
import Scenes.Main.LayerBase exposing (CommonData)
import Scenes.Main.UILayer.Export as UILayer


{-| LayerDataType
-}
type LayerDataType
    = GameLayerData GameLayer.Data
    | UILayerData UILayer.Data
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
